### ISSUE TITLE
NPM Install issues

### ISSUE THREAD

**Issue by Dradallor** [koktaildotcom/node-p1-reader#2]
Hi Guys,

So after being happy with this tool, I wanted to install it on a friends environment. He also had a Pi around, so we went for it; however, I keep getting below error, I tried this with Sudo and without but both cases same error message.

`pi@Schroempi:~/node-p1-reader $ sudo npm install
(node:9983) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! Including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.42-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/node-p1-reader
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node-p1-reader/npm-debug.log
npm ERR! not ok code 0
`

Any advice is welcome!

**Comment by Dradallor** [comment]
Please ignore, seems that sudo apt-get update on the latest stretch version will install node 8.1 instead of 12.x Removing 8.x and installing 12.x solved the biggest part of the issues
